//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int id_reserva { get; set; }
        public Nullable<System.DateTime> fecha_reserva { get; set; }
        public Nullable<System.TimeSpan> hora_inicio { get; set; }
        public Nullable<System.TimeSpan> hora_fin { get; set; }
        public Nullable<int> id_socio { get; set; }
        public string area { get; set; }
        public Nullable<int> id_instalacion { get; set; }
    
        public virtual Instalaciones Instalaciones { get; set; }
        public virtual Socio Socio { get; set; }
    }
}
